# read a set of text files, and create an include file for c++ 
# example: incgen shader.inc shader.frag shader.vert

import sys;

fileRead  = open( "istringconst.h", "r" )

match = "static grinliz::IString k"
defines = []
values = []

for line in fileRead:
	line = line.lstrip().rstrip()
	if ( line[0:len(match)] == match ):
		strConst = line[len(match):-1]
		defines.append( strConst )
		strConst = strConst.replace( "__", "." )
		values.append( strConst )

#for v in values :
#	print( v )

fileWrite = open( "istringconst.cpp", 'w' )

fileWrite.write( "// machine generated by istringconst.py\n" )
fileWrite.write( '#include "istringconst.h"\nusing namespace grinliz;\n\n' )

for v in defines:
	fileWrite.write( "IString IStringConst::k" + v + ";\n")

fileWrite.write( "\nvoid IStringConst::Init()\n{\n" )

for i in range(len(defines)):
	fileWrite.write( '\tk' + defines[i] + ' = StringPool::Intern( "' + values[i] + '", true );\n' )

fileWrite.write( "}\n")

