// machine generated by istringconst.py
#include "istringconst.h"
using namespace grinliz;

IString IStringConst::kmain;
IString IStringConst::ktrigger;
IString IStringConst::ktarget;
IString IStringConst::kalthand;
IString IStringConst::khead;
IString IStringConst::kshield;
IString IStringConst::khumanFemale;
IString IStringConst::khumanMale;
IString IStringConst::kworker;
IString IStringConst::kring;
IString IStringConst::klargeRing;
IString IStringConst::kgold;
IString IStringConst::kcrystal_green;
IString IStringConst::kcrystal_red;
IString IStringConst::kcrystal_blue;
IString IStringConst::kcrystal_violet;
IString IStringConst::kcore;
IString IStringConst::kkiosk__n;
IString IStringConst::kkiosk__m;
IString IStringConst::kkiosk__c;
IString IStringConst::kkiosk__s;

void IStringConst::Init()
{
	kmain = StringPool::Intern( "main", true );
	ktrigger = StringPool::Intern( "trigger", true );
	ktarget = StringPool::Intern( "target", true );
	kalthand = StringPool::Intern( "althand", true );
	khead = StringPool::Intern( "head", true );
	kshield = StringPool::Intern( "shield", true );
	khumanFemale = StringPool::Intern( "humanFemale", true );
	khumanMale = StringPool::Intern( "humanMale", true );
	kworker = StringPool::Intern( "worker", true );
	kring = StringPool::Intern( "ring", true );
	klargeRing = StringPool::Intern( "largeRing", true );
	kgold = StringPool::Intern( "gold", true );
	kcrystal_green = StringPool::Intern( "crystal_green", true );
	kcrystal_red = StringPool::Intern( "crystal_red", true );
	kcrystal_blue = StringPool::Intern( "crystal_blue", true );
	kcrystal_violet = StringPool::Intern( "crystal_violet", true );
	kcore = StringPool::Intern( "core", true );
	kkiosk__n = StringPool::Intern( "kiosk.n", true );
	kkiosk__m = StringPool::Intern( "kiosk.m", true );
	kkiosk__c = StringPool::Intern( "kiosk.c", true );
	kkiosk__s = StringPool::Intern( "kiosk.s", true );
}
