// WARNING: generated by blurmaker.py
uniform sampler2D texture0;
uniform float u_radius;
varying vec2 v_uv0;

void main() {
vec4 color=vec4(0.0, 0.0, 0.0, 0.0 );

#if BLUR_Y == 0

color += texture2D( texture0, v_uv0 - vec2( u_radius * 1.0 , 0.0 ) ) * 0.00979;
color += texture2D( texture0, v_uv0 - vec2( u_radius * 0.77778 , 0.0 ) ) * 0.02336;
color += texture2D( texture0, v_uv0 - vec2( u_radius * 0.55556 , 0.0 ) ) * 0.08978;
color += texture2D( texture0, v_uv0 - vec2( u_radius * 0.33333 , 0.0 ) ) * 0.1616;
color += texture2D( texture0, v_uv0 - vec2( u_radius * 0.11111 , 0.0 ) ) * 0.21547;
color += texture2D( texture0, v_uv0 + vec2( u_radius * 0.11111 , 0.0 ) ) * 0.21547;
color += texture2D( texture0, v_uv0 + vec2( u_radius * 0.33333 , 0.0 ) ) * 0.1616;
color += texture2D( texture0, v_uv0 + vec2( u_radius * 0.55556 , 0.0 ) ) * 0.08978;
color += texture2D( texture0, v_uv0 + vec2( u_radius * 0.77778 , 0.0 ) ) * 0.02336;
color += texture2D( texture0, v_uv0 + vec2( u_radius * 1.0 , 0.0 ) ) * 0.00979;

#else

color += texture2D( texture0, v_uv0 - vec2( 0.0, u_radius * 1.0 )) * 0.00979;
color += texture2D( texture0, v_uv0 - vec2( 0.0, u_radius * 0.77778 )) * 0.02336;
color += texture2D( texture0, v_uv0 - vec2( 0.0, u_radius * 0.55556 )) * 0.08978;
color += texture2D( texture0, v_uv0 - vec2( 0.0, u_radius * 0.33333 )) * 0.1616;
color += texture2D( texture0, v_uv0 - vec2( 0.0, u_radius * 0.11111 )) * 0.21547;
color += texture2D( texture0, v_uv0 + vec2( 0.0, u_radius * 0.11111 )) * 0.21547;
color += texture2D( texture0, v_uv0 + vec2( 0.0, u_radius * 0.33333 )) * 0.1616;
color += texture2D( texture0, v_uv0 + vec2( 0.0, u_radius * 0.55556 )) * 0.08978;
color += texture2D( texture0, v_uv0 + vec2( 0.0, u_radius * 0.77778 )) * 0.02336;
color += texture2D( texture0, v_uv0 + vec2( 0.0, u_radius * 1.0 )) * 0.00979;

#endif

gl_FragColor=color;
}
